### ISSUE TITLE
Only delete user-specific data on logout

### ISSUE THREAD

**Issue by bjrne** [openHPI/xikolo-ios#253]
We don't really nee to delete courses for example, enrollments should be enough. This would lead to a much better user experience as reloading and parsing the course page on openSAP might as well take 15-20 seconds.

**Subtasks:**
- [ ] Think about all entities that can stay
- [ ] Verify that all delete-rules are appropriate
- [ ] Adapt the `clearCoreDataStorage` method

**Comment by jprberlin** [comment]
based on your user you have permissions to see different courses. so not deleting them could lead to people seeing courses they dont have a permission to see

**Comment by bjrne** [comment]
oh right :/

**Comment by bjrne** [comment]
This is obsolete now, right @mathebox?

**Comment by mathebox** [comment]
Yes.
